create extension postgis;
create extension postgis_raster;
ALTER DATABASE satellite_data SET postgis.enable_outdb_rasters = true;
ALTER DATABASE satellite_data SET postgis.gdal_enabled_drivers TO 'ENABLE_ALL';
SET CLIENT_MIN_MESSAGES = 'DEBUG';
SET s3.aws_access_key_id TO 'L3dlmTg0qKVJB02w4VZx';
SET s3.aws_secret_access_key TO 'SlBBvoj5pPPHNQMFKG12ysAm5Opghx2JeI44ZYmg';
SET s3.aws_s3_endpoint TO '192.168.52.212:9200';
SET s3.aws_s3_verify TO 'NO';
SELECT pg_reload_conf();