create extension postgis;
create extension postgis_raster;
ALTER DATABASE satellite_data SET postgis.enable_outdb_rasters = true;
ALTER DATABASE satellite_data SET postgis.gdal_enabled_drivers TO 'ENABLE_ALL';
ALTER DATABASE satellite_data SET postgis.gdal_vsi_options = 'AWS_ACCESS_KEY_ID=L3dlmTg0qKVJB02w4VZx AWS_SECRET_ACCESS_KEY=SlBBvoj5pPPHNQMFKG12ysAm5Opghx2JeI44ZYmg';
ALTER DATABASE satellite_data SET CLIENT_MIN_MESSAGES = 'DEBUG';
ALTER DATABASE satellite_data SET s3.aws_access_key_id TO 'L3dlmTg0qKVJB02w4VZx';
ALTER DATABASE satellite_data SET s3.aws_secret_access_key TO 'SlBBvoj5pPPHNQMFKG12ysAm5Opghx2JeI44ZYmg';
ALTER DATABASE satellite_data SET s3.aws_s3_endpoint TO '192.168.52.212:9200';
ALTER DATABASE satellite_data SET s3.aws_s3_verify TO 'NO';
SELECT pg_reload_conf();